/*
 * Ingenic X3000 Halley8 minimal configuration.
 */
#ifndef __X3000_HALLEY8_H__
#define __X3000_HALLEY8_H__

#define CONFIG_MIPS32
#define CONFIG_CPU_XBURST2
#define CONFIG_SYS_LITTLE_ENDIAN
#define CONFIG_X3000

#ifndef CONFIG_SYS_UART_INDEX
#define CONFIG_SYS_UART_INDEX		7
#endif
#include "x3000_ddr.h"

#define CONFIG_SYS_APLL_FREQ		800000000
#define CONFIG_SYS_MPLL_FREQ		800000000
#define CONFIG_SYS_EPLL_FREQ		300000000
#define CONFIG_CPU_SEL_PLL		APLL
#define CONFIG_DDR_SEL_PLL		MPLL
#define CONFIG_SYS_CPU_FREQ		800000000
#define CONFIG_SYS_MEM_FREQ		200000000

#define CONFIG_SYS_AHB0_FREQ		200000000
#define CONFIG_SYS_AHB1_FREQ		200000000
#define CONFIG_SYS_AHB2_FREQ		200000000
#define CONFIG_SYS_PCLK_FREQ		100000000
#define CONFIG_SYS_LEP_FREQ		300000000

#define CGU_CLK_SRC {				\
		{DDR, MPLL},			\
		{MSC0, MPLL},			\
		{MSC1, MPLL},			\
		{MSC2, MPLL},			\
		{SFC, MPLL},			\
		{SRC_EOF, SRC_EOF}		\
	}

#define CONFIG_SYS_EXTAL		24000000
#define CONFIG_SYS_OST_FREQ		12500000
#define CONFIG_SYS_HZ			1000

#define CONFIG_SYS_DCACHE_SIZE		(32 * 1024)
#define CONFIG_SYS_DCACHELINE_SIZE	(32)
#define CONFIG_SYS_DCACHE_WAYS		(8)
#define CONFIG_SYS_ICACHE_SIZE		(32 * 1024)
#define CONFIG_SYS_ICACHELINE_SIZE	(32)
#define CONFIG_SYS_ICACHE_WAYS		(8)
#define CONFIG_SYS_CACHELINE_SIZE	(32)
#define CONFIG_BOARD_SCACHE
#define CONFIG_SYS_SCACHE_SIZE		(256 * 1024)
#define CONFIG_SYS_SCACHELINE_SIZE	(64)
#define CONFIG_SYS_SCACHE_WAYS		(8)

#define CONFIG_BAUDRATE			115200

#define CONFIG_BOOTARGS_AUTO_MODIFY	0
#if (CONFIG_BOOTARGS_AUTO_MODIFY == 1)
#define BOOTARGS_COMMON " console=ttyS0,115200 "
#else
#define BOOTARGS_COMMON " console=ttyS7,115200 mem=128M@0x0 "
#endif

#if defined(CONFIG_SPL_SFC_NOR)
#define X3000_BOOTARGS	"ip=off init=/linuxrc rootfstype=jffs2 root=/dev/mtdblock2 rw flashtype=nor"
#elif defined(CONFIG_SPL_SFC_NAND)
#define X3000_BOOTARGS	"ip=off init=/linuxrc ubi.mtd=2 root=ubi0:rootfs ubi.mtd=3 rootfstype=ubifs rw flashtype=nand"
#elif defined(CONFIG_JZ_MMC_MSC0)
#define X3000_BOOTARGS	" rootfstype=ext4 root=/dev/mmcblk0p7 rootdelay=3 rw"
#elif defined(CONFIG_JZ_MMC_MSC1)
#define X3000_BOOTARGS	" rootfstype=ext4 root=/dev/mmcblk1p7 rootdelay=3 rw"
#elif defined(CONFIG_JZ_MMC_MSC2)
#define X3000_BOOTARGS	" rootfstype=ext4 root=/dev/mmcblk2p7 rootdelay=3 rw"
#else
#define X3000_BOOTARGS	""
#endif

#define CONFIG_BOOTARGS BOOTARGS_COMMON X3000_BOOTARGS
#define CONFIG_BOOTDELAY 1
#if defined(CONFIG_SPL_SFC_NOR)
#define CONFIG_BOOTCOMMAND "sfcnor read 0x40000 0x600000 0x80a00000 ;bootm 0x80a00000"
#elif defined(CONFIG_SPL_SFC_NAND)
#define CONFIG_BOOTCOMMAND "sfcnand read 0x100000 0x600000 0x80a00000 ;bootm 0x80a00000"
#else
#define CONFIG_BOOTCOMMAND "mmc dev 0; mmc read 0x80a00000 0x1800 0x3000; bootm 0x80a00000"
#endif

/* MMC */
#if defined(CONFIG_JZ_MMC_MSC0) || defined(CONFIG_JZ_MMC_MSC1) || \
	defined(CONFIG_JZ_MMC_MSC2)
#define CONFIG_GENERIC_MMC
#define CONFIG_MMC
#define CONFIG_MMC_SPL_PARAMS
#define CONFIG_SDHCI
#define CONFIG_JZ_SDHCI
#define CONFIG_CMD_MMC
#define MSC_INIT_CLK            400000
#define MSC_WORKING_CLK		50000000
#endif

#ifdef CONFIG_JZ_MMC_MSC0
#define CONFIG_JZ_MMC_MSC0_PD
#define CONFIG_SPL_JZ_MSC_BUS_4BIT
#elif defined(CONFIG_JZ_MMC_MSC1)
#define CONFIG_JZ_MMC_MSC1_PD
#elif defined(CONFIG_JZ_MMC_MSC2)
#define CONFIG_JZ_MMC_MSC2_PD
#endif

#if defined(CONFIG_SPL_SFC_NOR) || defined(CONFIG_SPL_SFC_NAND)
#define CONFIG_SPL_SFC_SUPPORT
#define CONFIG_SPL_VERSION		1
#define CONFIG_SFC_V20
#define CONFIG_JZ_SFC_PD
#define CONFIG_SFC_RATE			48000000
#define CONFIG_SPIFLASH_PART_OFFSET	0x5800
#endif

#ifdef CONFIG_SPL_SFC_NOR
#define CONFIG_JZ_SFC
#define CONFIG_CMD_SFC_NOR
#define CONFIG_JZ_SFC_NOR
#define CONFIG_SPI_SPL_CHECK
#define CONFIG_SFC_NOR_RATE		200000000
#define CONFIG_SFC_QUAD
#define CONFIG_SPI_NORFLASH_PART_OFFSET	(CONFIG_SPIFLASH_PART_OFFSET + 0x74)
#define CONFIG_NOR_MAJOR_VERSION_NUMBER	1
#define CONFIG_NOR_MINOR_VERSION_NUMBER	0
#define CONFIG_NOR_REVERSION_NUMBER	0
#define CONFIG_NOR_VERSION	(CONFIG_NOR_MAJOR_VERSION_NUMBER | \
		(CONFIG_NOR_MINOR_VERSION_NUMBER << 8) | \
		(CONFIG_NOR_REVERSION_NUMBER << 16))
#endif

#ifdef CONFIG_SPL_SFC_NAND
#define CONFIG_JZ_SFC
#define CONFIG_CMD_SFCNAND
#define CONFIG_CMD_NAND
#define CONFIG_MTD_DEVICE
#define CONFIG_CMD_UBI
#define CONFIG_CMD_UBIFS
#define CONFIG_CMD_MTDPARTS
#define CONFIG_MTD_PARTITIONS
#define CONFIG_CMD_SAVEENV
#define CONFIG_SPI_SPL_CHECK
#define CONFIG_SFC_NAND_RATE		200000000
#define CONFIG_SFC_QUAD
#define CONFIG_SPI_NAND_BPP		(2048 + 64)
#define CONFIG_SPI_NAND_PPB		64
#define CONFIG_SYS_MAX_NAND_DEVICE	1
#define CONFIG_SYS_NAND_BASE		SFC_BASE
#define CONFIG_SYS_NAND_BLOCK_SIZE	(128 * 1024)
#define MTDIDS_DEFAULT			"nand0:nand"
#define MTDPARTS_DEFAULT			"mtdparts=nand:1M(boot),8M(kernel),40M(rootfs),-(data)"
#define CONFIG_SYS_NAND_SELF_INIT
#endif

#define CONFIG_SPL_PAD_TO		0x6000
#define CONFIG_SPL_MAX_SIZE		0x5800
#define CONFIG_UBOOT_OFFSET		CONFIG_SPL_PAD_TO

/* GPIO */
#define CONFIG_JZ_GPIO

/* Minimal command set for MSC boot/debug. */
#define CONFIG_CMD_BOOTD
#define CONFIG_CMD_CONSOLE
#define CONFIG_CMD_ECHO
#define CONFIG_CMD_EXT2
#define CONFIG_CMD_EXT4
#define CONFIG_CMD_FAT
#define CONFIG_USE_XYZMODEM
#define CONFIG_CMD_LOAD
#define CONFIG_CMD_LOADB
#define CONFIG_CMD_LOADS
#define CONFIG_CMD_MEMORY
#define CONFIG_CMD_MISC
#define CONFIG_CMD_RUN
#define CONFIG_CMD_SOURCE
#define CONFIG_CMD_GETTIME
#define CONFIG_CMD_GPIO
#define CONFIG_CMD_SAVEENV
#define CONFIG_EFI_PARTITION
#define CONFIG_DOS_PARTITION
#define CONFIG_LZO
#define CONFIG_RBTREE

#define CONFIG_SKIP_LOWLEVEL_INIT
#define CONFIG_BOARD_EARLY_INIT_F
#define CONFIG_SYS_NO_FLASH
#define CONFIG_SYS_FLASH_BASE		0
#define CONFIG_ENV_OVERWRITE
#define CONFIG_MISC_INIT_R		1

#define CONFIG_BOOTP_MASK		(CONFIG_BOOTP_DEFAUL)
#define CONFIG_SYS_MAXARGS		16
#define CONFIG_SYS_LONGHELP
#define CONFIG_SYS_PROMPT		CONFIG_SYS_BOARD "# "
#define CONFIG_SYS_CBSIZE		1024
#define CONFIG_SYS_PBSIZE		(CONFIG_SYS_CBSIZE + sizeof(CONFIG_SYS_PROMPT) + 16)

#define CONFIG_SYS_MONITOR_LEN		(512 * 1024)
#define CONFIG_SYS_MALLOC_LEN		(16 * 1024 * 1024)
#define CONFIG_SYS_BOOTPARAMS_LEN	(128 * 1024)

#define CONFIG_SYS_SDRAM_BASE		0x80000000
#define CONFIG_SYS_SDRAM_MAX_TOP	0x90000000
#define CONFIG_SYS_INIT_SP_OFFSET	0x400000
#define CONFIG_SYS_LOAD_ADDR		0x88000000
#define CONFIG_SYS_MEMTEST_START	0x80000000
#define CONFIG_SYS_MEMTEST_END		0x88000000

#define CONFIG_SYS_TEXT_BASE		0x80100000
#define CONFIG_SYS_SC_TEXT_BASE		0x80100004
#define CONFIG_SYS_MONITOR_BASE		CONFIG_SYS_TEXT_BASE

#ifdef CONFIG_ENV_IS_IN_MMC
#define CONFIG_SYS_MMC_ENV_DEV		0
#define CONFIG_ENV_SIZE			(32 << 10)
#define CONFIG_ENV_OFFSET		(CONFIG_SYS_MONITOR_LEN + CONFIG_SYS_MMCSD_RAW_MODE_U_BOOT_SECTOR * 512)

#elif defined(CONFIG_ENV_IS_IN_SFC)
#define CONFIG_CMD_SFC_NOR
#define CONFIG_ENV_SIZE			(4 << 10)
#define CONFIG_ENV_OFFSET		0x3f000
#define CONFIG_CMD_SAVEENV

#elif defined(CONFIG_SPL_SFC_NAND)
#define CONFIG_SYS_REDUNDAND_ENVIRONMENT
#define CONFIG_ENV_SECT_SIZE		CONFIG_SYS_NAND_BLOCK_SIZE
#define SPI_NAND_BLK			CONFIG_SYS_NAND_BLOCK_SIZE
#define CONFIG_ENV_SIZE			SPI_NAND_BLK
#define CONFIG_ENV_OFFSET		(CONFIG_SYS_NAND_BLOCK_SIZE * 6)
#define CONFIG_ENV_OFFSET_REDUND	(CONFIG_ENV_OFFSET + CONFIG_ENV_SIZE)
#define CONFIG_ENV_IS_IN_SFC_NAND
#endif

/* SPL */
#define CONFIG_SPL
#define CONFIG_SPL_FRAMEWORK
#define CONFIG_SPL_NO_CPU_SUPPORT_CODE
#define CONFIG_SPL_START_S_PATH		"$(CPUDIR)/$(SOC)"
#define CONFIG_SPL_LDSCRIPT		"$(CPUDIR)/$(SOC)/u-boot-spl.lds"
#define CONFIG_SPL_BOARD_INIT
#define CONFIG_SPL_LIBGENERIC_SUPPORT
#define CONFIG_SPL_GPIO_SUPPORT
#define CONFIG_SPL_SERIAL_SUPPORT
#define CONFIG_SPL_TEXT_BASE		0x80001000

#if defined(CONFIG_SPL_MMC_SUPPORT) || defined(CONFIG_SPL_JZMMC_SUPPORT)
#define CONFIG_SYS_MMCSD_RAW_MODE_U_BOOT_SECTOR	82
#ifdef CONFIG_SPL_JZMMC_SUPPORT
#define CONFIG_SPL_JZSDHCI
#endif
#ifdef CONFIG_SPL_MMC_SUPPORT
#define CONFIG_JZ_MMC_SPLMSC
#endif
#define CONFIG_GPT_TAB_BUILT_IN
#endif

#ifdef CONFIG_GPT_CREATOR
#define CONFIG_GPT_TABLE_PATH		"$(TOPDIR)/board/$(BOARDDIR)"
#endif

#endif /* __X3000_HALLEY8_H__ */
