stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

before_script:
  - echo "Before script section"
  - echo "setup cross compile toolchain mips-linux-gnu-gcc"
  - /etc/gitlab-runner/bin/mips-linux-gnu-gcc -v
  - export PATH=/etc/gitlab-runner/bin:$PATH
  - mips-linux-gnu-gcc -v

include:
   - local: .gitlab/ci/x16xx.yml
   - local: .gitlab/ci/x2000.yml
   - local: .gitlab/ci/x2500.yml
   - local: .gitlab/ci/x26xx.yml

test-job:
    stage: test
    script:
      - echo "Test stage ..."


deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  environment: production
  script:
    - echo "Deploying stage ..."


